apiVersion: apps/v1
kind: Deployment
metadata:
  name: small
spec:
  replicas: 1
  selector:
    matchLabels:
      app: small
  template:
    metadata:
      labels:
        app: small
    spec:
      containers:
      - image: okteto.dev/small:latest
        name: small
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "85be19d1-c59d-40d3-9f4a-81ba9653de96"
        - name: Vless_Path
          value: "/s233"
        - name: Vmess_UUID
          value: "85be19d1-c59d-40d3-9f4a-81ba9653de96"
        - name: Vmess_Path
          value: "/s234"
        - name: Share_Path
          value: "/Share233"
